require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-md

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/Documentation:
  Exclude:
    - 'app/**/*'
    - 'config/**/*'
    - 'spec/**/*'